[package]
name = "nekoflow-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
thiserror.workspace = true
nekoflow-macros = { path = "../nekoflow-macros" }
tokio = { workspace = true, features = ["full"] }
anyhow = "1.0.98"
